os: osx
osx_image: xcode10.2

langugage: bash

install:
  - whoami
  - echo "Start of Pipleine"
  - HOMEBREW_NO_AUTO_UPDATE=1
 
git:
  depth: false
  
cache:
   -directories:
     -$HOME/Library/Caches/Homebrew
   
script:
  - ls
  - chmod +x hello.sh
  - ./hello.sh
  - docker pull scratch
  
after_script:
  - echo "End of Pipline"
